Workflow: upgrade setup-elixir action to 1.6.0
astarte-platform/astarte_vmq_plugin pull request #42
Opened 2021-03-03 15:53 UTC by Annopaolo

Upgrade actions/setup-elixir@1.5.0 to erlef/setup-elixir@1.6.0.

Signed-off-by: Arnaldo Cesco <arnaldo.cesco@ispirata.com>

2021-03-03 16:01 UTC, rbino requested changes

2021-03-03 16:01 UTC, rbino commented on .github/workflows/build-workflow.yaml
> +    - uses: erlef/setup-elixir@1.6.0
You're missing a `v`, it should be:
```
erlef/setup-elixir@v1.6.0
```

2021-03-03 16:01 UTC, rbino commented on .github/workflows/build-workflow.yaml
> +    - uses: erlef/setup-elixir@1.6.0
See above

2021-03-04 10:04 UTC, Annopaolo commented on .github/workflows/build-workflow.yaml
> +    - uses: erlef/setup-elixir@1.6.0
Done, thanks

2021-03-04 10:04 UTC, Annopaolo commented on .github/workflows/build-workflow.yaml
> +    - uses: erlef/setup-elixir@1.6.0
Done, thanks

2021-03-04 10:14 UTC, rbino approved these changes

2021-03-04 10:14 UTC, merged